apiVersion: apps/v1
kind: Deployment
metadata:
  name: loans-r-us
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loanservice
  template:
    metadata:
      labels:
        app: loanservice
    spec:
      containers:
        - name: loanservice
          image: derekmitchell399/loanservice:v0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: loanservice
  namespace: default
spec:
  type: NodePort
  selector:
    app: loanservice
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
